# Generated by Django 4.0.5 on 2022-10-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=20)),
                ('card_description', models.TextField()),
                ('card_image', models.ImageField(default='', upload_to='card_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(default='', upload_to='home_pic')),
                ('akshay_pic', models.ImageField(default='', upload_to='home_pic')),
                ('akshay_background', models.ImageField(default='', upload_to='home_pic')),
                ('akshay_resume', models.FileField(default='', upload_to='home_pic')),
                ('akshay_cv', models.FileField(default='', upload_to='home_pic')),
            ],
        ),
    ]
