# Generated by Django 4.0.5 on 2022-10-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_image', models.ImageField(default='', upload_to='certificate_pic')),
                ('certificate_title', models.CharField(max_length=20)),
                ('certificate_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(default='', upload_to='gallery_pic')),
                ('gallery_img_title', models.CharField(max_length=20)),
                ('gallery_img_about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(default='', upload_to='project_pic')),
                ('project_title', models.CharField(max_length=15)),
                ('project_description', models.TextField()),
                ('project_link', models.TextField()),
            ],
        ),
    ]
