# Generated by Django 4.0.5 on 2022-10-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certificate_gallery_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='akshay_background',
            new_name='aki_background',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='akshay_cv',
            new_name='aki_cv',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='akshay_pic',
            new_name='aki_pic',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='akshay_resume',
            new_name='aki_resume',
        ),
    ]
