# Generated by Django 4.0.5 on 2022-10-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_akshay_background_image_aki_background_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=20)),
                ('about_image', models.ImageField(upload_to='home_pic')),
                ('about_description', models.TextField()),
            ],
        ),
    ]
