# Generated by Django 4.0.5 on 2022-10-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='aki_cv',
        ),
        migrations.RemoveField(
            model_name='image',
            name='aki_resume',
        ),
    ]
