# Generated by Django 4.0.5 on 2022-10-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_image_aki_cv_remove_image_aki_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='aki_pic_title',
            field=models.CharField(default='my_pics', max_length=20),
        ),
    ]
